## Problem Definition & Data Understanding

### 🔹Business Problem

E-news Express, an online news portal, aims to expand its business by acquiring new subscribers. 

Below are the key measures  

todo: need to add more details

### 🔹Questions to Answer

- Do users spend more time on new page?
- Is conversion rate higher?
- Does conversion depend on language?
- Does time spent differ across languages?

### 🔹Data Description

|column_name|description|
|--|--|
|user_id | Unique visitor|
|group| control vs treatment|
|landing_page| new vs old|
|time_spent_on_the_page| Time (in minutes)|
|converted| become subscriber (yes/no)
|language_preferred | language|

### 🔹 Inital Checks

In [2]:
#Importing common libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
# Loading the dataset
original_data = pd.read_csv('dataset/abtest.csv')

In [5]:
df = original_data.copy()

In [6]:
# Displaying the first 5 rows of the dataset
df.head()

,user_id,group,landing_page,time_spent_on_the_page,converted,language_preferred
0,546592,control,old,3.48,no,Spanish
1,546468,treatment,new,7.13,yes,English
2,546462,treatment,new,4.40,no,Spanish
3,546567,control,old,3.02,no,French
4,546459,treatment,new,4.75,yes,Spanish

In [7]:
# Displaying the summary of the dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   user_id                 100 non-null    int64
 1   group                   100 non-null    object
 2   landing_page            100 non-null    object
 3   time_spent_on_the_page  100 non-null    float64
 4   converted               100 non-null    object
 5   language_preferred      100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB

In [9]:
# Displaying the statistical summary of the dataset
df.describe()

             user_id  time_spent_on_the_page
count     100.000000              100.000000
mean   546517.000000                5.377800
std        52.295779                2.378166
min    546443.000000                0.190000
25%    546467.750000                3.880000
50%    546492.500000                5.415000
75%    546567.250000                7.022500
max    546592.000000               10.710000

In [10]:
# Checking for missing values in the dataset
df.isna().sum()

user_id                   0
group                     0
landing_page              0
time_spent_on_the_page    0
converted                 0
language_preferred        0
dtype: int64

In [12]:
# Checking for duplicate values in the dataset
df.duplicated().sum()

np.int64(0)

> No missing values deducted. Dataset is ready for analysis

## Exploratory Data Analysis (EDA)